### ISSUE TITLE
Training Maxbot to take surveys.

### ISSUE THREAD

**Issue by jamalv** [teamforus/chat.forus.io#10]
Related to: https://github.com/teamforus/foundation/issues/23

The proposed enquête consists of 17 statements that you rate on a scale of one to 6.

It can look something like this:

<img width="712" alt="screenshot 2018-10-02 at 09 33 18" src="https://user-images.githubusercontent.com/30194799/46334943-367cb700-c626-11e8-9434-4ec55f1c2656.png">

**Comment by maxvisser** [comment]
Did some research for this feature. I came to the conclusion Maxbot is great for asking questions but him asking you questions is much harder.

An easy way to solve this issue is using the same maxbot command as the standup message and sending a survey link instead of directly asking questions.

**Comment by maxvisser** [comment]
as issue 23 is closed and I have no clear direction on how to tackle this I will close it for now.
