### ISSUE TITLE
Teamleader webhook

### ISSUE THREAD

**Issue by maxvisser** [teamforus/chat.forus.io#11]
**Is your feature request related to a problem? Please describe.**
Logging in to teamleader to see your notifications is a bit of a hassle

**Describe the solution you'd like**
Make use of the teamleader webhooks and api

**Comment by maxvisser** [comment]
need to be admin on teamleader to make a webhook there.

**Comment by jamalv** [comment]
<img width="459" alt="screenshot 2018-10-07 at 11 13 47" src="https://user-images.githubusercontent.com/30194799/46580282-1c761680-ca22-11e8-8a13-a5cac2c02c04.png">

**Comment by jamalv** [comment]
I think that's @maartenfv

**Comment by maartenfv** [comment]
@maxvisser Can this one be closed?
