### ISSUE TITLE
translate livechat to dutch and remove rocket.chat logo

### ISSUE THREAD

**Issue by maxvisser** [teamforus/chat.forus.io#12]
![image](https://user-images.githubusercontent.com/10818702/48066405-c71e5800-e1cd-11e8-8b91-f477b6c6e05a.png)

**Comment by maxvisser** [comment]
to solve this issue, I had to set our rocket.chat standard to Dutch...

**Comment by maxvisser** [comment]
removing rocket.chat logo is not possible with using a Snap

**Comment by jamalv** [comment]
The Dutch translations in rocket.chat are poor, and since we have an international team I really dislike it being in dutch.

**Comment by jamalv** [comment]
Let's investigate if we can come up with something better.

**Comment by maxvisser** [comment]
Imo i think investigating running rocket.chat without snap is the way to go

**Comment by jamalv** [comment]
I guess that will mean we can make changes to the source?

**Comment by jamalv** [comment]
probably with higher maintenance costs? manual updates etc?

**Comment by maxvisser** [comment]
yes we could set in the code of livechat that we want to use dutch, also we can implement our own design for livechat.

**Comment by danrminds** [comment]
Alex did a design for the chat widget, in the PSD with the sign-up flow

**Comment by maxvisser** [comment]
the psd can be accessed from here: https://github.com/teamforus/forus/issues/320 ;)

**Comment by maxvisser** [comment]
I am already starting with making a chat.forus.link on aws :)
