### ISSUE TITLE
Turn of 'has joined the channel' messages?

### ISSUE THREAD

**Issue by jamalv** [teamforus/chat.forus.io#5]
## Description

The messages have the potential to clutter the channels a bit, do we want this? In the #general channel I think its no problem but in other channels it might start distracting from the conversations at some point. 

Curious to hear your comments

**Comment by maxvisser** [comment]
can you use the issue template. https://github.com/teamforus/repository-standards/blob/master/ISSUE_TEMPLATE.md

**Comment by maxvisser** [comment]
I don't see why we should turn off these messages. There are not alot of people joining... If we turn them off we could replace it with Maxbot saying 'welcome! @jamalv '

**Comment by jamalv** [comment]
Updated the description, agree it's not a problem yet, but it might become distracting at some point. 

For new members I think it's more interesting to see the conversations, especially in the topic channels. It might be good to only leave them on for the #general channel, and indeed maybe even replace them with a custom greeting from Maxbot (that would be cool!)

**Comment by maxvisser** [comment]
Disabled 'user1 joined' and added a hubot warm welcome scripts

**Comment by jamalv** [comment]
the welcome script doesn't seem to work yet 😕

**Comment by maxvisser** [comment]
I re enabled this feature will look at this again in the future.

**Comment by maxvisser** [comment]
Reinstalled the welcome script. looks like it enabled.

**Comment by maxvisser** [comment]
This issue is fixed with the latest addition of maxbot; a welcome script

**Comment by jamalv** [comment]
that’s awesome
