### ISSUE TITLE
Error uploading files into channels

### ISSUE THREAD

**Issue by maartenfv** [teamforus/chat.forus.io#8]
### Description:

I get an error when trying to upload drive files such as gsheets into a channel. Not sure to which files this is applicable.

### Steps to reproduce:

1. In our team channel
2. Click upload file
3. Pick a file from my device
4. Selected and click upload
5. Gives error in the form of a pop-up: application/vnd.google-apps.spreadsheet with a red cross above.

### Expected behavior:

I want to be able to upload files.

**Comment by maxvisser** [comment]
there are no restriction on file upload
