### ISSUE TITLE
Telegram bridge

### ISSUE THREAD

**Issue by jamalv** [teamforus/chat.forus.io#9]
## Problem

Part of the team is communicating trough telegram. This fragments communication. Now sometimes the rest of the team doesn’t know what’s going on.

# Solution

If we build a bridge between telegram and rocket chat, we will have one place again where everyone can check in and see what’s happening. Even if we would have some different language channels, we would still see activity, which is assuring :)

## Resources:
https://sameroom.io/integrations/connect-rocketchat-and-telegram
https://rocket.chat/docs/administrator-guides/integrations/telegram/

**Comment by jamalv** [comment]
Sameroom looks smooth, but it's not free: https://sameroom.io/pricing

**Comment by maxvisser** [comment]
Could make a hubot plugin and create a telegram bot that will basically repplay messages

**Comment by jamalv** [comment]
that sounds lovely

**Comment by maxvisser** [comment]
done. #forus on our chat is connected to a forus group on telegram.
